### ISSUE TITLE
using translated still results in many queries

### ISSUE THREAD

**Issue by czpython** [edoburu/django-parler#96] opened 2015-07-10 22:23 UTC
Hello,

I'm trying out parler and noticed that when using ```Article.language('de').translated('de')``` and iterating over it, it causes a query for every single article instead of doing a prefetch. Was this intended behavior? or I'm I doing something wrong?

Example:

```
In [11]: articles = Article.objects.language('de').translated('de')

In [12]: print articles
SELECT "aldryn_newsblog_article"."id",
       "aldryn_newsblog_article"."content_id",
       "aldryn_newsblog_article"."author_id",
       "aldryn_newsblog_article"."owner_id",
       "aldryn_newsblog_article"."app_config_id",
       "aldryn_newsblog_article"."publishing_date",
       "aldryn_newsblog_article"."is_published",
       "aldryn_newsblog_article"."is_featured",
       "aldryn_newsblog_article"."featured_image_id",
       "filer_file"."id",
       "filer_file"."polymorphic_ctype_id",
       "filer_file"."folder_id",
       "filer_file"."file",
       "filer_file"."_file_size",
       "filer_file"."sha1",
       "filer_file"."has_all_mandatory_data",
       "filer_file"."original_filename",
       "filer_file"."name",
       "filer_file"."description",
       "filer_file"."owner_id",
       "filer_file"."uploaded_at",
       "filer_file"."modified_at",
       "filer_file"."is_public",
       "filer_image"."file_ptr_id",
       "filer_image"."_height",
       "filer_image"."_width",
       "filer_image"."default_alt_text",
       "filer_image"."default_caption",
       "filer_image"."subject_location",
       "filer_image"."date_taken",
       "filer_image"."author",
       "filer_image"."must_always_publish_author_credit",
       "filer_image"."must_always_publish_copyright"
FROM "aldryn_newsblog_article"
INNER JOIN "aldryn_newsblog_article_translation" ON ("aldryn_newsblog_article"."id" = "aldryn_newsblog_article_translation"."master_id")
LEFT OUTER JOIN "filer_image" ON ("aldryn_newsblog_article"."featured_image_id" = "filer_image"."file_ptr_id")
LEFT OUTER JOIN "filer_file" ON ("filer_image"."file_ptr_id" = "filer_file"."id")
WHERE "aldryn_newsblog_article_translation"."language_code" = 'de'
ORDER BY "aldryn_newsblog_article"."publishing_date" DESC LIMIT 21 [3.37ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 251
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.37ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 248
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.89ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 247
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.59ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 242
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.50ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 236
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.75ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 243
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.47ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 235
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.47ms]
SELECT "aldryn_newsblog_article_translation"."id",
       "aldryn_newsblog_article_translation"."language_code",
       "aldryn_newsblog_article_translation"."title",
       "aldryn_newsblog_article_translation"."slug",
       "aldryn_newsblog_article_translation"."lead_in",
       "aldryn_newsblog_article_translation"."meta_title",
       "aldryn_newsblog_article_translation"."meta_description",
       "aldryn_newsblog_article_translation"."meta_keywords",
       "aldryn_newsblog_article_translation"."search_data",
       "aldryn_newsblog_article_translation"."master_id"
FROM "aldryn_newsblog_article_translation"
WHERE ("aldryn_newsblog_article_translation"."master_id" = 230
       AND "aldryn_newsblog_article_translation"."language_code" = 'de') [0.30ms]```

**Comment by vdboor** [comment] 2015-07-30 09:28
Hi,

Yes, you're missing the `.prefetch_related('translations')` call.
It's indeed intended behavior, because each individual translation will be in memcached at the next round. Hence, you'll find it uses very few queries during the next request.

* The `language("de")` call only makes sure the retrieved objects have their current language set to "de".
* The `translated("de")` call returns the objects which are translated in in "de". You can also use that method to filter the translations.

**Closed by vdboor** 2015-07-30 09:28 UTC
